- name: Ensure group {{ az_dev_agent_group }} exists
  group:
    name: "{{ az_dev_agent_group }}"
    state: present

- name: Add a dev_agent user
  user:
    name: "{{ az_dev_agent_user }}"
    group: "{{ az_dev_agent_group }}"
    uid: "{{ az_dev_agent_uid|default(omit) }}"
    comment: "Azure DevOps Agent"
    shell: /bin/bash
  become: true

- name: Create directories for the dev_agent
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ az_dev_agent_user }}"
    group: "{{ az_dev_agent_group }}"
    mode: 1755
  loop:
    - "{{ az_dev_agent_folder }}"
    - "{{ az_devops_work_folder }}"
  become: true

- name: Download vsts-agent.tar.gz file
  get_url:
    url: "{{ az_devops_default_agent_package_url }}"
    dest: /home/{{ az_dev_agent_user }}/vsts-agent-linux-x64.tar.gz
    owner: "{{ az_dev_agent_user }}"
    group: "{{ az_dev_agent_group }}"

- name: Extract vsts-agent.tar.gz file
  become: true
  unarchive:
    src: /home/{{  az_dev_agent_user }}/vsts-agent-linux-x64.tar.gz
    dest: "{{ az_devops_default_agent_folder }}"
    owner: "{{ az_dev_agent_user }}"
    group: "{{ az_dev_agent_group }}"

