---
- debug:
    msg:
    - "Dependency lookup variables are :"
    - "{{ ansible_system }}.yml"

- name: Read platform-specific variables
  include_vars: "{{ varfile }}"
  with_first_found:
    - files:
        - "{{ ansible_system }}.yml"
      skip: true
  loop_control:
    loop_var: varfile

- name: Read platform specific tasks
  include_tasks: "{{ taskfile }}"
  with_first_found:
    - "{{ ansible_system }}.yml"
  loop_control:
    loop_var: taskfile
